PythonControlApp/blueprints/MovePanel.py
import threading
import time
from flask import jsonify, redirect, render_template, request, url_for
from Arduino.ArduinoSerialCommunication import InitArduinoConnection
import Robot.Robot as Robot
from flask import Blueprint

movePanelBlueprint = Blueprint('MovePanelBlueprint', __name__)

increment_values = [1, 0.5, 0.1, 0.05]

@movePanelBlueprint.route('/movePanel')
def movePanel():
    InitArduinoConnection()

    Robot.MoveInBasePos()

    return render_template('movePanel.html', Robot = Robot, increment_values = increment_values)

@movePanelBlueprint.route('/increment/<int:index>', methods=['POST'])
def increment(index):
    increment_value = increment_values[int(request.form['increment_type'])]
    Robot.xyz[index]['value'] += increment_value
    Robot.MoveInBasePos()

    return render_template('movePanel.html', Robot = Robot, increment_values = increment_values)

@movePanelBlueprint.route('/decrement/<int:index>', methods=['POST'])
def decrement(index):
    increment_value = increment_values[int(request.form['increment_type'])]
    Robot.xyz[index]['value'] -= increment_value
    Robot.MoveInBasePos()

    return render_template('movePanel.html', Robot = Robot, increment_values = increment_values)

PythonControlApp/blueprints/ProgramList.py
from flask import jsonify, redirect, render_template, request, url_for
import Robot.Robot as Robot
from flask import Blueprint

programListBlueprint = Blueprint('ProgramListBlueprint', __name__)


@programListBlueprint.route('/element/<int:index>', methods=['GET', 'POST'])
def element_details(index):
    selected_element = Robot.program[index - 1].positions
    print(selected_element)
    if request.method == 'POST':
        for i, value in enumerate(selected_element):
            selected_element[i] = int(request.form.get(f'value_{i+1}'))

    return render_template('element_details.html', selected_element=selected_element)

@programListBlueprint.route('/get_current_number')
def get_current_number():
    return jsonify(number=Robot.currentPosition)

PythonControlApp/blueprints/ProgramPanel.py
from flask import Blueprint, render_template
import Robot.RobotController as RobotController

programPanelBlueprint = Blueprint('ProgramPanelBlueprint', __name__)

@programPanelBlueprint.route('/programPanel')
def program_panel():

    return render_template('programPanel.html', RobotController = RobotController), 200

PythonControlApp/blueprints/RepeatPanel.py
import threading
from flask import jsonify, render_template, request
import Robot.Robot as Robot
from flask import Blueprint

repeatPanelBlueprint = Blueprint('RepeatPanelBlueprint', __name__)

@repeatPanelBlueprint.route("/repeatPanel", methods=['GET', 'POST'])
def repeat_panel():
    localIp = request.remote_addr

    result = None
    if request.method == 'POST':
        filename = request.form['filename']
        action = request.form.get('action')
        
        if action == 'write':
            result = Robot.write_json_file(filename=filename)
        elif action == 'overwrite':
            result = Robot.write_json_file(filename=filename, override=True)
        elif action == 'read':
            result = Robot.read_json_file(filename=filename)
    
    return render_template('repeatPanel.html', Robot=Robot, result = result), 200

@repeatPanelBlueprint.route('/run_once', methods=['POST'])
def run_once():
    if not Robot.running:
        Robot.running = True
        Robot.running_thread = threading.Thread(target=Robot.RunProgramOnce)
        Robot.running_thread.start()
        print("The program started running")
    return jsonify(status='started')

@repeatPanelBlueprint.route('/run_forever', methods=['POST'])
def run_forever():
    if not Robot.running:
        Robot.running = True
        Robot.running_thread = threading.Thread(target=Robot.RunProgramForever)
        Robot.running_thread.start()
        print("The program started running")
    return jsonify(status='started')

@repeatPanelBlueprint.route('/stop_printing', methods=['POST'])
def stop_printing():
    if Robot.running:
        Robot.running = False
        Robot.running_thread.join()  # Wait for the thread to finish
        print("The program stopped running")
    return jsonify(status='stopped')

PythonControlApp/blueprints/TeachPanel.py
import threading
import time
from flask import jsonify, redirect, render_template, url_for
from Arduino.ArduinoSerialCommunication import InitArduinoConnection
import Robot.Robot as Robot
from flask import Blueprint

teachPanelBlueprint = Blueprint('TeachPanelBlueprint', __name__)


@teachPanelBlueprint.route('/teachPanel')
def teachPanel():
    InitArduinoConnection()

    # time.sleep(1000)
    Robot.SwitchToTeachMode()

    return render_template('teachPanel.html', Robot = Robot)

@teachPanelBlueprint.route('/AddPositionFromServoPos', methods=['GET', 'POST'])
def AddPositionFromServoPos():
    Robot.AddPositionFromServoPos(-1)
    redirect(url_for('/teachPanel'))

# @app.route('/remove/<item>', methods=['POST'])
# def remove_item(item):
#     Robot.program.pop(int(item) - 1)

#     # if item in Robot.program:
#     #     print("da")
#     return redirect(url_for('teachPanel'))

@teachPanelBlueprint.route('/remove/<item_index>', methods=['POST'])
def remove_item(item_index):
    index = int(item_index) - 1
    if 0 <= index < len(Robot.program):
        Robot.program.pop(index)
    return redirect(url_for('teachPanel'))

@teachPanelBlueprint.route('/reorder/<from_index>/<to_index>', methods=['POST'])
def reorder_items(from_index, to_index):
    from_index = int(from_index)
    to_index = int(to_index)
    if 0 <= from_index < len(Robot.program) and 0 <= to_index < len(Robot.program):
        element = Robot.program.pop(from_index)
        Robot.program.insert(to_index, element)
    return redirect(url_for('teachPanel'))

PythonControlApp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Gippu</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>
<body style="background-color: #1a1a1a">
    <header class="header">
        <nav class="navbar">
            <ul class="nav-list">
                <li><a href="{{ url_for('ProgramPanelBlueprint.program_panel') }}">Program Panel</a></li>
                <li><a href="{{ url_for('RepeatPanelBlueprint.repeat_panel') }}">Repeat Panel</a></li>
                <li><a href="{{ url_for('TeachPanelBlueprint.teachPanel') }}">Teach Panel</a></li>
                <li><a href="{{ url_for('MovePanelBlueprint.movePanel') }}">Move Panel</a></li>
            </ul>
        </nav>
    </header>

    <main>
        {% block main %}
        {% endblock %}
    </main>

    <footer>
        <!-- Common footer content -->
    </footer>
</body>
</html>

PythonControlApp/templates/components/file_manager.html
<h1>File Operations</h1>

<form method="post">
    <input type="text" name="filename" placeholder="Enter file name"
        value="{{ RobotController.loadedProgram if result != 'File already exists. Do you want to overwrite it?' else RobotController.programToOverwrite }}"
        required>
    <button type="submit" name="action" value="read">Read File</button>
    <button type="submit" name="action" value="write">Write File</button>
    {% if result == "File already exists. Do you want to overwrite it?" %}
    <button type="submit" name="action" value="overwrite">Overwrite</button>
    {% endif %}
</form>
{% if result %}
<h2>Result:</h2>
<pre>{{ result }}</pre>
{% endif %}

PythonControlApp/templates/element_details.html
{% extends "base.html" %}

{% block main %}
<div class = "centered-container">
    <a href="/">Back To Repeat Panel</a>
<!-- </div>

<div> -->
    <h3>Vector Values:</h3>
<!-- </div>

<div> -->
    <form method="post">
        {% for value in selected_element %}
        <label for="value_{{ loop.index }}">{{ loop.index }}:</label>
        <input type="text" id="value_{{ loop.index }}" name="value_{{ loop.index }}" value="{{ value }}">
    </br>
        {% endfor %}
        <button type="submit">Save</button>
    </form>
</div>
{% endblock %}

PythonControlApp/templates/event.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Event</title>
</head>
<body>
    <p> {{ name }} </p>
</body>
</html>

PythonControlApp/templates/movePanel.html
{% extends "base.html" %}

{% block main %}


<div id="container">
    <h2>Program</h2>
    <!-- {% include 'programList.html' %} -->


    <h2>Move Panel</h2>
    <div class="move-main-panel">

        {% for number_set in Robot.xyz %}
            <div class="xyz_column">
            <h2>{{ number_set['name'] }}</h2>
            <p>Value:  {{ number_set['value']|round(2) }}</p>
            {% set axis = loop.index0 %}
            
            {% for increment in increment_values %}
                <form method="POST" action="/increment/{{ axis }}">
                    <button class="button" type="submit">Increment by {{ increment }}</button>
                    <input type="hidden" name="increment_type" value="{{ loop.index0 }}">
                </form>
                <form method="POST" action="/decrement/{{ axis }}">
                    <button class="button" type="submit">Decrement by {{ increment }}</button>
                    <input type="hidden" name="increment_type" value="{{ loop.index0 }}">
                </form>
            {% endfor %}
            </div>
        {% endfor %}

        <script>
            document.getElementById("add-position-button").addEventListener("click", function () {
                fetch("/AddPositionFromServoPos", { method: "POST" })
                    .then(() => window.location.reload());
            });
        </script>
    </div>
</div>
{% endblock %}

PythonControlApp/templates/programList.html
<ul class="fancy-list" id="sortable-list">
    
    {% for element in Robot.program %}
    <li draggable="true" data-index="{{ loop.index }}">
        <div> <h5>{{ loop.index }}&nbsp&nbsp</h5> </div>
        <a href="{{ url_for('ProgramListBlueprint.element_details', index=loop.index) }}">{{ element.positions }}</a>
        <button class="remove-button" data-item="{{ loop.index }}">Remove</button>
    </li>
    {% endfor %}

    <form method="POST" action="/update">
        <label for="new_number">Current Position:</label>
        <input type="number" id="current_number_input" name="new_number" value="{{ number }}" required>
        <button type="submit">Change Number</button>
    </form>

    <!-- Add a hidden input to store the current number -->
    <!-- <input type="hidden" id="current_number_input" value="{{ number }}"> -->

</ul>
<script>
const removeButtons = document.querySelectorAll('.remove-button');
removeButtons.forEach(button => {
    button.addEventListener('click', function() {
        const itemToRemove = this.getAttribute('data-item');
        fetch(`/remove/${itemToRemove}`, { method: 'POST' })
            .then(() => window.location.reload());
    });
});

const sortableList = document.getElementById('sortable-list');
let draggedItem = null;

sortableList.addEventListener('dragstart', e => {
    draggedItem = e.target;
    e.dataTransfer.setData('text/plain', draggedItem.dataset.index);
    draggedItem.style.opacity = '0.5';
});

sortableList.addEventListener('dragend', e => {
    draggedItem.style.opacity = '1';
});

sortableList.addEventListener('dragover', e => {
    e.preventDefault();
    const targetItem = e.target;
    if (targetItem.nodeName === 'LI') {
        targetItem.style.border = '2px dashed #ccc';
    }
});

sortableList.addEventListener('dragleave', e => {
    const targetItem = e.target;
    if (targetItem.nodeName === 'LI') {
        targetItem.style.border = 'none';
    }
});

sortableList.addEventListener('drop', e => {
    e.preventDefault();
    const targetItem = e.target;
    if (targetItem.nodeName === 'LI') {
        targetItem.style.border = 'none';
        const fromIndex = Number(draggedItem.dataset.index) - 1;
        const toIndex = Number(targetItem.dataset.index) - 1;
        console.log(fromIndex)
        console.log(toIndex)
        // Update the order on the server using fetch or AJAX
        fetch(`/reorder/${fromIndex}/${toIndex}`, { method: 'POST' })
            .then(() => window.location.reload());
    }
});

function updateNumberField() {
    // Fetch the current number from the server
    fetch('/get_current_number')
        .then(response => response.json())
        .then(data => {
            // Update the input field and the displayed current number
            const currentNumberInput = document.getElementById('current_number_input');
            currentNumberInput.value = data.number + 1;
        });
}

// Periodically update the input field (e.g., every 5 seconds)
setInterval(updateNumberField, 500);

// Initial update when the page loads
updateNumberField();
</script>

PythonControlApp/templates/programPanel.html
{% extends "base.html" %}

{% block main %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.12/ace.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.12/ext-language_tools.js"></script>


<div id="container">
    <h2>Program Panel</h2>
    <div class="program-main-panel">
        <div class="program-text-editor">
            <div id="editor" style="height: 500px; width: 100%;">function hello() { console.log("Hello, world!"); }
            </div>
        </div>
        <div class="program-info">
            {% include 'components/file_manager.html' %}

            <h3>Da</h3>
        </div>
    </div>
</div>

<script>
    // Initialize the editor
    var editor = ace.edit("editor");
    editor.setTheme("ace/theme/monokai");
    editor.session.setMode("ace/mode/javascript");

    // Enable options
    editor.setOptions({
        enableBasicAutocompletion: true,
        enableSnippets: true,
        enableLiveAutocompletion: false
    });

    // Example of setting keyboard shortcuts
    editor.commands.addCommand({
        name: 'moveLineUp',
        bindKey: { win: 'Alt-Up', mac: 'Alt-Up' },
        exec: function (editor) {
            editor.moveLinesUp();
        }
    });

    editor.commands.addCommand({
        name: 'moveLineDown',
        bindKey: { win: 'Alt-Down', mac: 'Alt-Down' },
        exec: function (editor) {
            editor.moveLinesDown();
        }
    });
</script>
{% endblock %}

PythonControlApp/templates/repeatPanel.html
{% extends "base.html" %}

{% block main %}
<div>
    <h2>Program</h2>
    {% include 'programList.html' %}

    <h2>Repeat Panel</h2>
    <!-- Content for repeat panel -->
    <div id="repeat-mode-main-panel">

        <h1>File Operations</h1>
        <form method="post">
            <input type="text" name="filename" placeholder="Enter file name" value="{{ Robot.loadedProgram if result != 'File already exists. Do you want to overwrite it?' else Robot.programToOverwrite }}" required>
            <!-- onclick="if(this.value == 'Enter file name') { this.value = ''; }" onblur="if(this.value == '') { this.value = 'Enter file name'; }"> -->
            <button type="submit" name="action" value="read">Read File</button>
            <button type="submit" name="action" value="write">Write File</button>
            {% if result == "File already exists. Do you want to overwrite it?" %}
                <button type="submit" name="action" value="overwrite">Overwrite</button>
            {% endif %}
        </form>
        {% if result %}
            <h2>Result:</h2>
            <pre>{{ result }}</pre>
        {% endif %}

        <div class="centered-container">
            <div class="column">
                <button id="run-once-button" {% if Robot.running %}disabled{% endif %}>Run Once</button>
                <button id="run-forever-button" {% if Robot.running %}disabled{% endif %}>Run Forever</button>
            </div>
            <div class="column">
                <button id="stop-button" {% if not Robot.running %}disabled{% endif %}>Stop Running</button>
            </div>
        </div>

        <script>
            $(document).ready(function () {
                $('#run-once-button').click(function () {
                    $.post('/run_once', function (data) {
                        $('#run-once-button').prop('disabled', true);
                        $('#run-forever-button').prop('disabled', true);
                        $('#stop-button').prop('disabled', false);
                        refreshStatus();
                    });
                });

                $('#run-forever-button').click(function () {
                    $.post('/run_forever', function (data) {
                        $('#run-once-button').prop('disabled', true);
                        $('#run-forever-button').prop('disabled', true);
                        $('#stop-button').prop('disabled', false);
                        refreshStatus();
                    });
                });

                $('#stop-button').click(function () {
                    $.post('/stop_printing', function (data) {
                        $('#run-once-button').prop('disabled', false);
                        $('#run-forever-button').prop('disabled', false);
                        $('#stop-button').prop('disabled', true);
                        refreshStatus();
                    });
                });

                function refreshStatus() {
                    $.get('/', function (data) {
                        // console.log(data.Robot.running)
                        if (data.Robot.running) {
                            $('#run-once-button').prop('disabled', true);
                            $('#run-forever-button').prop('disabled', true);
                            $('#stop-button').prop('disabled', false);
                        } else {
                            $('#run-once-button').prop('disabled', false);
                            $('#run-forever-button').prop('disabled', false);
                            $('#stop-button').prop('disabled', true);
                        }
                    });
                }

                // Refresh the status every 2 seconds
                setInterval(refreshStatus, 2000);
            });
        </script>
    </div>
</div>
</br>
</br>
<!-- {% if personel|length > 0 %}
        <div id="lab-open-status-box">The lab is open. Come on in.</div>
        </br>
        <div id="who-is-in-lab-list">Who is in the lab right now:
        </br>
        </br>
            <tbody>
                {% for name in personel %}
                    <tr>
                        <td>{{ name }}</br></td>
                    </tr>
                {% endfor %}
            </tbody>
        </div>
    {% else %}
        <div id="lab-closed-status-box">The lab is empty right now.</div>
    {% endif %} -->
</br>
</br>
</br>
<!-- {% if inTeam == False %}
    <div id="join-team-database">
        <h2>Join the team by entering your name</h2>
        <form action="/addtoteam" method="get">
            <input name="name" type="text" onblur="this.value=removeSpaces(this.value);">
            <input type="submit">
        </form>
    </div>
     {% else %} -->
<!-- <h2 id="join-team-database">You are already in the team</h2> -->
<!-- {% endif %} -->
{% endblock %}

PythonControlApp/templates/teachPanel.html
{% extends "base.html" %}

{% block main %}


<div id="container">
    <h2>Program</h2>
    {% include 'programList.html' %}
    

    <h2>Teach Panel</h2>
    <div id="repeat-mode-main-panel">
        <button id="add-position-button">Add Position from servo</button>

        <script>
            document.getElementById("add-position-button").addEventListener("click", function () {
                fetch("/AddPositionFromServoPos", { method: "POST" })
                    .then(() => window.location.reload());
            });
        </script>
    </div>
</div>
{% endblock %}